Add BOASwap documents
bosagora/docs-biznet pull request #12
Opened 2022-06-27 03:28 UTC by TrustHenry

For BOASwap

2022-06-30 05:31 UTC, Kang-Simon approved these changes

2022-06-30 06:46 UTC, TrustHenry commented
I will modify the image path and rebuild it.

2022-07-06 05:56 UTC, MichaelKim20 requested changes
확인해 주세요

2022-07-06 05:56 UTC, MichaelKim20 commented on config/en/mkdocs.yml
> +        - Myassets:
```suggestion
        - My Assets:
```

2022-07-06 05:56 UTC, MichaelKim20 commented on config/kr/mkdocs.yml
> +        - 나의자산: boa_swap/myassets/myassets.md
```suggestion
        - 나의 자산: boa_swap/myassets/myassets.md
```

2022-07-06 06:23 UTC, TrustHenry commented on config/en/mkdocs.yml
> +        - Myassets:
The suggestion applied.

2022-07-06 06:23 UTC, TrustHenry commented on config/kr/mkdocs.yml
> +        - 나의자산: boa_swap/myassets/myassets.md
The suggestion applied.

2022-07-06 07:31 UTC, MichaelKim20 approved these changes

2022-07-06 07:31 UTC, merged